name: Build and upload "binaries"

on: 
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        shell: bash
        run: echo "and KGrzeg" >> greetings.txt
      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          path: greetings.txt
          name: linux
      - name: Log files
        run: ls -alR 
      - uses: svenstaro/upload-release-action@v2
        name: Upload directly text file
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: greetings.txt
          tag: ${{ github.ref }}
      - uses: papeloto/action-zip@v1
        name: Zip greetings
        with:
          files: greetings.txt
          dest: zipgreet.zip
      - uses: svenstaro/upload-release-action@v2
        name: Upload directly archive
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zipgreet-version-$tag.zip
          tag: ${{ github.ref }}

  release-assets:
    name: Publish 
    needs: [release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux]
    steps:
      - uses: actions/checkout@master
        name: maybe just need checkout
      - uses: actions/download-artifact@v2
        name: Grab ${{ matrix.platform }}
        with:
          name: ${{ matrix.platform }}
          path: ${{ matrix.platform }}.zip
      - name: Log files
        run: ls -alR
      - uses: svenstaro/upload-release-action@v2
        name: Upload ${{ matrix.platform }} to release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.platform }}.zip
          asset_name: "linlinlinlinux.zip"
          tag: ${{ github.ref }}
          body: "Are files attached?"
      
